# Generated by Django 2.2.6 on 2019-10-15 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodComuna', models.IntegerField(max_length=3)),
                ('Descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodUsuario', models.IntegerField(max_length=5)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RutUsuario', models.CharField(max_length=8)),
                ('DvUsuario', models.CharField(max_length=1)),
                ('Nombre', models.CharField(max_length=100)),
                ('ApellidoPaterno', models.CharField(max_length=50)),
                ('ApellidoMaterno', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=12)),
                ('CodComuna', models.IntegerField(verbose_name=4)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorUsuarios.TipoUsuario')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestorUsuarios.Usuario')),
            ],
        ),
    ]
